config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
# Company
	resources :companies, only: [:new, :create] do
		collection do
			get 'welcome'
		end
	end

# Devise - User Authentication
  	devise_for :users

# Calendar
 	resources :calendars, only: [:index]

# Leads
	resources :leads do
		collection do
			get 'view_lead'
			get 'dashboard'
			get 'report'
		end
	end

# Accounts
	resources :accounts do
		collection do
			get 'view_account'
			get 'dashboard'
			get 'report'
		end
	end

# Contacts
	resources :contacts do
		collection do
			get 'view_contact'
			get 'dashboard'
			get 'report'
		end
	end

# Activities
	resources :phone_calls do
		collection do
			get 'view_call'
			get 'dashboard'
			get 'report'
		end
	end
	resources :events do
		collection do
			get 'view_event'
			get 'dashboard'
			get 'report'
		end
	end
	resources :tasks do
	  	collection do
	  		get 'view_task'
	  		get 'dashboard'
	  		get 'report'
	  	end
	end

# Invoices & Orders
	resources :purchase_orders do
		collection do
			get 'view_order'
			get 'dashboard'
			get 'report'
		end
	end
	resources :sales_orders do
		collection do
			get 'view_order'
			get 'dashboard'
			get 'report'
		end
	end
	resources :invoices do
		collection do
			get 'view_invoice'
			get 'dashboard'
			get 'report'
		end
	end

# Quotes and More
	resources :quotes do
		collection do
			get 'view_quote'
			get 'dashboard'
			get 'report'
		end
	end
	resources :price_books do
		collection do
			get 'view_book'
			get 'dashboard'
			get 'report'
		end
	end

# Vendor
	resources :vendors do
		collection do
			get 'view_vendor'
			get 'dashboard'
			get 'report'
		end
	end

# Products and More
	resources :products do
		collection do
			get 'view_product'
			get 'dashboard'
			get 'report'
		end
	end

	resources :cases do
		collection do
			get 'view_case'
			get 'dashboard'
			get 'report'
		end
	end

	resources :solutions do
		collection do
			get 'view_solution'
			get 'dashboard'
			get 'report'
		end
	end

# Potentials
	resources :potentials do
		collection do
			get 'view_potential'
			get 'dashboard'
			get 'report'
		end
	end

# Appointments
	resources :appointments do
		collection do
			get 'view_appointment'
			get 'dashboard'
			get 'report'
		end
	end

# Campaigns
	resources :campaigns do
		collection do
			get 'view_campaign'
			get 'dashboard'
			get 'report'
		end
	end

# Landing Page
root 'leads#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base

	# Relationships
	belongs_to :company
	belongs_to :potential
	belongs_to :quote_stage
	belongs_to :contact
	belongs_to :account
	belongs_to :quote_owner, class_name: "User", foreign_key: "owner"

	# Delegates
	# delegate :name, to: :potential, prefix: true, allow_nil: true
	delegate :name, to: :quote_stage, prefix: true, allow_nil: true
	# delegate :name, to: :contact, prefix: true, allow_nil: true
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def index
    @quotes = current_company.quotes
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = current_company.quotes.build(quote_params)
    if @quote.save
      redirect_to quotes_path
    else
      render :new
    end
  end

  def show
    @quote = Quote.find(params[:id])
  end

  def edit
    @quote = Quote.find(params[:id])
  end

  def update
    @quote = Quote.find(params[:id])
    if @quote.update(quote_params)
      redirect_to quotes_path
    else
      render :edit
    end
  end

  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy
    redirect_to quotes_path
  end

  def view_quote
    @quote = Quote.find(params[:id])
    render layout: false
  end

   # Dashboard
  def dashboard
    
  end

    # Report
  def report
    @quotes = current_company.quotes
    respond_to do |format|
      format.xlsx
    end
  end

  private

  def quote_params
    params.require(:quote).permit(:name, :owner, :potential_id, :quote_stage_id, :valid_till, :contact_id, :account_id)
  end
end

app/views/quotes/_form.html.erb
<div class="form-group">
	<label class="control-label">Quote Subject</label>
	<%= f.text_field :name, class: "form-control" %>
	<% if quote.errors[:name].present? %>
    	<div class="error-message"><%=  quote.errors[:name][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Owner</label>
	<%= f.collection_select :owner, User.all, :id, :email, {}, class: "form-control" %>
	<% if quote.errors[:owner].present? %>
    	<div class="error-message"><%=  quote.errors[:owner][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Valid Till</label>
	<%= f.date_select :valid_till, class: "form-control", prompt: true %>
	<% if quote.errors[:valid_till].present? %>
    	<div class="error-message"><%=  quote.errors[:valid_till][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Potential</label>
	<%= f.text_field :potential_id, class: "form-control" %>
	<% if quote.errors[:potential_id].present? %>
    	<div class="error-message"><%=  quote.errors[:potential_id][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Contact</label>
	<%= f.text_field :contact_id, class: "form-control" %>
	<% if quote.errors[:contact_id].present? %>
    	<div class="error-message"><%=  quote.errors[:contact_id][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Account</label>
	<%= f.text_field :account_id, class: "form-control" %>
	<% if quote.errors[:account_id].present? %>
    	<div class="error-message"><%=  quote.errors[:account_id][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Quote Stage</label>
	<%= f.collection_select :quote_stage_id, QuoteStage.all, :id, :name, {}, class: "form-control" %>
	<% if quote.errors[:quote_stage_id].present? %>
    	<div class="error-message"><%=  quote.errors[:quote_stage_id][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<%= f.submit "Save", class: "btn btn-warning" %>
	<%= link_to "Back", quotes_path , class: "btn btn-primary" %>
</div>

app/views/quotes/edit.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-10">
			<div class="page-header">
				<h1><small>Edit Quote</small></h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-offset-2 col-lg-5">
			<%= form_for @quote do |f| %>
				<%= render 'form', :f => f, :quote => @quote %>
			<% end %>
		</div>
	</div>
</div>

app/views/quotes/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="page-header">
				<h1>
					<small><i class="fa fa-pencil-square-o"></i> Quote</small>
					<div class="pull-right">
						<%= link_to "<i class='fa fa-plus'></i> New Quote".html_safe, new_quote_path, class: "btn btn-warning btn-sm" %>
						<%= link_to "<i class='fa fa-bar-chart-o'></i> Dashboard".html_safe, dashboard_quotes_path, class: "btn btn-success btn-sm" %>
						<%= link_to "<i class='fa fa-file-excel-o'></i> Report".html_safe, report_quotes_path(:format => :xlsx), class: "btn btn-danger btn-sm" %>
					</div>
				</h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-offset-1 col-lg-10">
			<table class="table table-striped table-hover">
				<tr class="warning">
					<th></th>
					<th>Name</th>
					<th>Owner</th>
					<th>Valid Till</th>
					<th>Actions</th>
				</tr>
				<% @quotes.each do |quote| %>
					<tr>
						<td></td>
						<td><a href="#" onclick="get_click(<%= quote.id %>);"><%= quote.name %></a></td>
						<td><%= quote.owner %></td>
						<td><%= quote.valid_till %></td>
						<td>
							<%= link_to content_tag(:i,nil, class: 'fa fa-pencil'), edit_quote_path(quote), class: "btn btn-success btn-xs table-actions" %>
							<%#= link_to content_tag(:i,nil, class: 'fa fa-eye'), quote_path(quote), class: "btn btn-info btn-xs table-actions" %>
							<%= link_to content_tag(:i,nil, class: 'fa fa-trash'), quote, class: "btn btn-danger btn-xs table-actions", method: :delete %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>	
</div>

<script type="text/javascript">
	function get_click(quote){
	$('#view_quote').modal({
  	 remote: "/quotes/view_quote?id=" + quote
	});
	$('#view_quote').on('hidden.bs.modal', function () {
 	location.reload();
	})
	}
</script>

<div class="modal fade" id="view_quote" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/quotes/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-10">
			<div class="page-header">
				<h1><small>New Quote</small></h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-offset-2 col-lg-5">
			<%= form_for @quote do |f| %>
				<%= render 'form', :f => f, :quote => @quote %>
			<% end %>
		</div>
	</div>
</div>

app/views/quotes/show.html.erb
<h1>Quotes#show</h1>
<p>Find me in app/views/quotes/show.html.erb</p>

app/views/quotes/view_quote.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <h4 class="modal-title" id="myModalLabel">Quote Information</h4>
</div>
<div class="modal-body">
	<div class="form-group">
		<label>Title</label>
		<p><%= @quote.name %></p>
	</div>
	<div class="form-group">
		<label>Owner</label>
		<p><%= @quote.owner %></p>
	</div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
  <%= link_to "Edit", edit_quote_path(@quote), class: "btn btn-warning" %>
</div>