config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
# Company
	resources :companies, only: [:new, :create] do
		collection do
			get 'welcome'
		end
	end

# Devise - User Authentication
  	devise_for :users

# Calendar
 	resources :calendars, only: [:index]

# Leads
	resources :leads do
		collection do
			get 'view_lead'
			get 'dashboard'
			get 'report'
		end
	end

# Accounts
	resources :accounts do
		collection do
			get 'view_account'
			get 'dashboard'
			get 'report'
		end
	end

# Contacts
	resources :contacts do
		collection do
			get 'view_contact'
			get 'dashboard'
			get 'report'
		end
	end

# Activities
	resources :phone_calls do
		collection do
			get 'view_call'
			get 'dashboard'
			get 'report'
		end
	end
	resources :events do
		collection do
			get 'view_event'
			get 'dashboard'
			get 'report'
		end
	end
	resources :tasks do
	  	collection do
	  		get 'view_task'
	  		get 'dashboard'
	  		get 'report'
	  	end
	end

# Invoices & Orders
	resources :purchase_orders do
		collection do
			get 'view_order'
			get 'dashboard'
			get 'report'
		end
	end
	resources :sales_orders do
		collection do
			get 'view_order'
			get 'dashboard'
			get 'report'
		end
	end
	resources :invoices do
		collection do
			get 'view_invoice'
			get 'dashboard'
			get 'report'
		end
	end

# Quotes and More
	resources :quotes do
		collection do
			get 'view_quote'
			get 'dashboard'
			get 'report'
		end
	end
	resources :price_books do
		collection do
			get 'view_book'
			get 'dashboard'
			get 'report'
		end
	end

# Vendor
	resources :vendors do
		collection do
			get 'view_vendor'
			get 'dashboard'
			get 'report'
		end
	end

# Products and More
	resources :products do
		collection do
			get 'view_product'
			get 'dashboard'
			get 'report'
		end
	end

	resources :cases do
		collection do
			get 'view_case'
			get 'dashboard'
			get 'report'
		end
	end

	resources :solutions do
		collection do
			get 'view_solution'
			get 'dashboard'
			get 'report'
		end
	end

# Potentials
	resources :potentials do
		collection do
			get 'view_potential'
			get 'dashboard'
			get 'report'
		end
	end

# Appointments
	resources :appointments do
		collection do
			get 'view_appointment'
			get 'dashboard'
			get 'report'
		end
	end

# Campaigns
	resources :campaigns do
		collection do
			get 'view_campaign'
			get 'dashboard'
			get 'report'
		end
	end

# Landing Page
root 'leads#index'

end

app/models/task.rb
class Task < ActiveRecord::Base

	# Acossiations
	belongs_to :company
	belongs_to :task_category
	belongs_to :task_status
	belongs_to :priority
	belongs_to :task_owner, class_name: "User", foreign_key: "owner"

	# Delegate
	delegate :name, to: :task_category, prefix: true, allow_nil: true
	delegate :name, to: :task_status, prefix: true, allow_nil: true
	delegate :name, to: :priority, prefix: true, allow_nil: true

	# Validation
	validates :name, presence: true
	validates :name, uniqueness: {scope: :company_id}
	validates :due_date, presence: true
	validates :owner, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = current_company.tasks
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_company.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  def view_task
    @task = Task.find(params[:id])
    render layout: false
  end

   # Dashboard
  def dashboard
    
  end

    # Report
  def report
    @tasks = current_company.tasks
    respond_to do |formart|
      formart.xlsx
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :due_date, :owner, :task_category_id, :task_status_id, :priority_id, :notes)
  end
end

app/views/tasks/_form.html.erb
<div class="form-group">
	<label class="control-label">Task Name</label>
	<%= f.text_field :name, class: "form-control" %>
	<% if task.errors[:name].present? %>
    	<div class="error-message"><%=  task.errors[:name][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	 <label class="control-label">Due Date</label>
	 <%= f.date_select :due_date, class: "form-control", prompt: true%>
	 <% if task.errors[:due_date].present? %>
    	<div class="error-message"><%=  task.errors[:due_date][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Owner</label>
	<%= f.collection_select :owner, User.all, :id, :email, {}, class: "form-control" %>
	<% if task.errors[:owner].present? %>
    	<div class="error-message"><%=  task.errors[:owner][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Owner</label>
	<%= f.collection_select :task_category_id, TaskCategory.all, :id, :name, {}, class: "form-control" %>
	<% if task.errors[:task_category_id].present? %>
    	<div class="error-message"><%=  task.errors[:task_category_id][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Status</label>
	<%= f.collection_select :task_status_id, TaskStatus.all, :id, :name, {}, class: "form-control" %>
	<% if task.errors[:task_status_id].present? %>
    	<div class="error-message"><%=  task.errors[:task_status_id][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Priority</label>
	<%= f.collection_select :priority_id, Priority.all, :id, :name, {}, class: "form-control" %>
	<% if task.errors[:priority_id].present? %>
    	<div class="error-message"><%=  task.errors[:priority_id][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Notes</label>
	<%= f.text_area :notes, class: "form-control" %>
	<% if task.errors[:notes].present? %>
    	<div class="error-message"><%=  task.errors[:notes][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<%= f.submit "Save", class: "btn btn-warning" %>
	<%= link_to "Back", tasks_path , class: "btn btn-primary" %>
</div>

app/views/tasks/edit.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-10">
			<div class="page-header">
				<h1><small>Edit Task</small></h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-offset-2 col-lg-5">
			<%= form_for @task do |f| %>
				<%= render 'form', :f => f, :task => @task %>
			<% end %>
		</div>
	</div>
</div>

app/views/tasks/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="page-header">
				<h1>
					<small><i class="fa fa-check-square-o"></i> Tasks</small>
					<div class="pull-right">
						<%= link_to "<i class='fa fa-plus'></i> New Task".html_safe, new_task_path, class: "btn btn-warning btn-sm" %>
						<%= link_to "<i class='fa fa-bar-chart-o'></i> Dashboard".html_safe, dashboard_tasks_path, class: "btn btn-success btn-sm" %>
						<%= link_to "<i class='fa fa-file-excel-o'></i> Report".html_safe, report_tasks_path(:format => :xlsx), class: "btn btn-danger btn-sm" %>
					</div>
				</h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-offset-1 col-lg-10">
			<table class="table table-striped table-hover">
				<tr class="warning">
					<th></th>
					<th>Name</th>
					<th>Owner</th>
					<th>Due Date</th>
					<th>Status</th>
					<th>Priority</th>
					<th>Actions</th>
				</tr>
				<% @tasks.each do |task| %>
					<tr>
						<td></td>
						<td><a href="#" onclick="get_click(<%= task.id %>);"><%= task.name %></a></td>
						<td><%= task.owner %></td>
						<td><%= task.due_date %></td>
						<td><%= task.task_status_name %></td>
						<td><%= task.priority_name %></td>
						<td>
							<%= link_to content_tag(:i,nil, class: 'fa fa-pencil'), edit_task_path(task), class: "btn btn-success btn-xs table-actions" %>
							<%#= link_to content_tag(:i,nil, class: 'fa fa-eye'), task_path(task), class: "btn btn-info btn-xs table-actions" %>
							<%= link_to content_tag(:i,nil, class: 'fa fa-trash'), task, class: "btn btn-danger btn-xs table-actions", method: :delete %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>	
</div>

<script type="text/javascript">
	function get_click(task){
	$('#add_comment').modal({
  	 remote: "/tasks/view_task?id=" + task
	});
	$('#add_comment').on('hidden.bs.modal', function () {
 	location.reload();
	})
	}
</script>

<div class="modal fade" id="add_comment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-10">
			<div class="page-header">
				<h1><small>New Task</small></h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-offset-2 col-lg-5">
			<%= form_for @task do |f| %>
				<%= render 'form', :f => f, :task => @task %>
			<% end %>
		</div>
	</div>
</div>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

app/views/tasks/view_task.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <h4 class="modal-title" id="myModalLabel">Task Information</h4>
</div>
<div class="modal-body">
	<div class="form-group">
		<label>Title</label>
		<p><%= @task.name %></p>
	</div>
	<div class="form-group">
		<label>Due Date</label>
		<p><%= @task.due_date %></p>
	</div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
  <%= link_to "Edit", edit_task_path(@task), class: "btn btn-warning" %>
</div>