config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
# Company
	resources :companies, only: [:new, :create] do
		collection do
			get 'welcome'
		end
	end

# Devise - User Authentication
  	devise_for :users

# Calendar
 	resources :calendars, only: [:index]

# Leads
	resources :leads do
		collection do
			get 'view_lead'
			get 'dashboard'
			get 'report'
		end
	end

# Accounts
	resources :accounts do
		collection do
			get 'view_account'
			get 'dashboard'
			get 'report'
		end
	end

# Contacts
	resources :contacts do
		collection do
			get 'view_contact'
			get 'dashboard'
			get 'report'
		end
	end

# Activities
	resources :phone_calls do
		collection do
			get 'view_call'
			get 'dashboard'
			get 'report'
		end
	end
	resources :events do
		collection do
			get 'view_event'
			get 'dashboard'
			get 'report'
		end
	end
	resources :tasks do
	  	collection do
	  		get 'view_task'
	  		get 'dashboard'
	  		get 'report'
	  	end
	end

# Invoices & Orders
	resources :purchase_orders do
		collection do
			get 'view_order'
			get 'dashboard'
			get 'report'
		end
	end
	resources :sales_orders do
		collection do
			get 'view_order'
			get 'dashboard'
			get 'report'
		end
	end
	resources :invoices do
		collection do
			get 'view_invoice'
			get 'dashboard'
			get 'report'
		end
	end

# Quotes and More
	resources :quotes do
		collection do
			get 'view_quote'
			get 'dashboard'
			get 'report'
		end
	end
	resources :price_books do
		collection do
			get 'view_book'
			get 'dashboard'
			get 'report'
		end
	end

# Vendor
	resources :vendors do
		collection do
			get 'view_vendor'
			get 'dashboard'
			get 'report'
		end
	end

# Products and More
	resources :products do
		collection do
			get 'view_product'
			get 'dashboard'
			get 'report'
		end
	end

	resources :cases do
		collection do
			get 'view_case'
			get 'dashboard'
			get 'report'
		end
	end

	resources :solutions do
		collection do
			get 'view_solution'
			get 'dashboard'
			get 'report'
		end
	end

# Potentials
	resources :potentials do
		collection do
			get 'view_potential'
			get 'dashboard'
			get 'report'
		end
	end

# Appointments
	resources :appointments do
		collection do
			get 'view_appointment'
			get 'dashboard'
			get 'report'
		end
	end

# Campaigns
	resources :campaigns do
		collection do
			get 'view_campaign'
			get 'dashboard'
			get 'report'
		end
	end

# Landing Page
root 'leads#index'

end

app/models/potential.rb
class Potential < ActiveRecord::Base

	# Relationships
	has_many :sales_orders
	has_many :quotes
	belongs_to :company
	belongs_to :potential_owner, class_name: "User", foreign_key: "owner"
	belongs_to :contact
	belongs_to :account
	belongs_to :potential_stage
	belongs_to :potential_type
	belongs_to :lead_source
	belongs_to :campaign

	# Delegates
	delegate :name, to: :account, prefix: true, allow_nil: true
	delegate :f_name, to: :contact, prefix: true, allow_nil: true
	delegate :name, to: :potential_type, prefix: true, allow_nil: true
	delegate :name, to: :potential_stage, prefix: true, allow_nil: true
	delegate :name, to: :lead_source, prefix: true, allow_nil: true
	delegate :name, to: :campaign, prefix: true, allow_nil: true

end

app/models/potential_type.rb
class PotentialType < ActiveRecord::Base

	# Relationships
	has_many :potentials
end

app/controllers/potentials_controller.rb
class PotentialsController < ApplicationController

  def index
    @potentials = current_company.potentials
  end

  def new
    @potential = Potential.new
  end

  def create
    @potential = current_company.potentials.build(potential_params)
    if @potential.save
      redirect_to potentials_path
    else
      render :new
    end
  end

  def show
    @potential = Potential.find(params[:id])
  end

  def edit
    @potential = Potential.find(params[:id])
  end

  def update
    @potential = Potential.find(params[:id])
    if @potential.update(potential_params)
      redirect_to potentials_path
    else
      render :edit
    end
  end

  def destroy
    @potential = Potential.find(params[:id])
    @potential.destroy
    redirect_to potentials_path
  end

  def view_potential
    @potential = Potential.find(params[:id])
    render layout: false
  end

   # Dashboard
  def dashboard
    
  end

    # Report
  def report
    @potentials = current_company.potentials
    respond_to do |format|
      format.xlsx
    end
  end

  private

  def potential_params
    params.require(:potential).permit(:name, :owner, :amount, :contact_id, :closing_date, :account_id, :potential_stage_id, :potential_type_id, :probability, :next_step, :expected_revenue, :lead_source_id, :campaign_id)
  end
end

app/views/potentials/_form.html.erb
<div class="form-group">
	<label class="control-label">Name</label>
	<%= f.text_field :name, class: "form-control" %>
	<% if potential.errors[:name].present? %>
    	<div class="error-message"><%=  potential.errors[:name][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Amount</label>
	<%= f.text_field :amount, class: "form-control" %>
	<% if potential.errors[:amount].present? %>
    	<div class="error-message"><%=  potential.errors[:amount][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Contact</label>
	<%= f.collection_select :contact_id, current_company.contacts.all, :id, :name, {}, class: "form-control" %>
	<% if potential.errors[:contact_id].present? %>
    	<div class="error-message"><%=  potential.errors[:contact_id][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Closing Date</label>
	<%= f.date_select :closing_date, class: "form-control", prompt: true %>
	<% if potential.errors[:closing_date].present? %>
    	<div class="error-message"><%=  potential.errors[:closing_date][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Account</label>
	<%= f.collection_select :account_id, current_company.contacts.all, :id, :name, {}, class: "form-control" %>
	<% if potential.errors[:account_id].present? %>
    	<div class="error-message"><%=  potential.errors[:account_id][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Owner</label>
	<%= f.collection_select :owner, User.all, :id, :email, {}, class: "form-control" %>
	<% if potential.errors[:owner].present? %>
    	<div class="error-message"><%=  potential.errors[:owner][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Potential Stage</label>
	<%= f.collection_select :potential_stage_id, PotentialStage.all, :id, :name, {}, class: "form-control" %>
	<% if potential.errors[:potential_stage_id].present? %>
    	<div class="error-message"><%=  potential.errors[:potential_stage_id][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Potential Type</label>
	<%= f.collection_select :potential_type_id, PotentialType.all, :id, :name, {}, class: "form-control" %>
	<% if potential.errors[:potential_type_id].present? %>
    	<div class="error-message"><%=  potential.errors[:potential_type_id][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Probability</label>
	<%= f.text_field :probability, class: "form-control" %>
	<% if potential.errors[:probability].present? %>
    	<div class="error-message"><%=  potential.errors[:probability][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Next Step</label>
	<%= f.text_field :next_step, class: "form-control" %>
	<% if potential.errors[:next_step].present? %>
    	<div class="error-message"><%=  potential.errors[:next_step][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Expected Revenue</label>
	<%= f.text_field :expected_revenue, class: "form-control" %>
	<% if potential.errors[:expected_revenue].present? %>
    	<div class="error-message"><%=  potential.errors[:expected_revenue][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Campaigns</label>
	<%= f.collection_select :campaign_id, current_company.campaigns.all, :id, :name, {}, class: "form-control" %>
	<% if potential.errors[:campaign_id].present? %>
    	<div class="error-message"><%=  potential.errors[:campaign_id][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Lead Source</label>
	<%= f.collection_select :lead_source_id, LeadSource.all, :id, :name, {}, class: "form-control" %>
	<% if potential.errors[:lead_source_id].present? %>
    	<div class="error-message"><%=  potential.errors[:lead_source_id][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<%= f.submit "Save", class: "btn btn-warning" %>
	<%= link_to "Back", potentials_path , class: "btn btn-primary" %>
</div>

app/views/potentials/edit.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-10">
			<div class="page-header">
				<h1><small>Edit Potential</small></h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-offset-2 col-lg-5">
			<%= form_for @potential do |f| %>
				<%= render 'form', :f => f, :potential => @potential %>
			<% end %>
		</div>
	</div>
</div>

app/views/potentials/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="page-header">
				<h1>
					<small><i class="fa fa-users"></i> Potentials</small>
					<div class="pull-right">
						<%= link_to "<i class='fa fa-plus'></i> New Potential".html_safe, new_potential_path, class: "btn btn-warning btn-sm" %>
						<%= link_to "<i class='fa fa-bar-chart-o'></i> Dashboard".html_safe, dashboard_potentials_path, class: "btn btn-success btn-sm" %>
						<%= link_to "<i class='fa fa-file-excel-o'></i> Report".html_safe, report_potentials_path(:format => :xlsx), class: "btn btn-danger btn-sm" %>
					</div>
				</h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-offset-1 col-lg-10">
			<table class="table table-striped table-hover">
				<tr class="warning">
					<th></th>
					<th>Name</th>
					<th>Owner</th>
					<th>Actions</th>
				</tr>
				<% @potentials.each do |potential| %>
					<tr>
						<td></td>
						<td><a href="#" onclick="get_click(<%= potential.id %>);"><%= potential.name %></a></td>
						<td><%= potential.owner %></td>
						<td>
							<%= link_to content_tag(:i,nil, class: 'fa fa-pencil'), edit_potential_path(potential), class: "btn btn-success btn-xs table-actions" %>
							<%#= link_to content_tag(:i,nil, class: 'fa fa-eye'), potential_path(potential), class: "btn btn-info btn-xs table-actions" %>
							<%= link_to content_tag(:i,nil, class: 'fa fa-trash'), potential, class: "btn btn-danger btn-xs table-actions", method: :delete %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>	
</div>

<script type="text/javascript">
	function get_click(potential){
	$('#view_potential').modal({
  	 remote: "/potentials/view_potential?id=" + potential
	});
	$('#view_potential').on('hidden.bs.modal', function () {
 	location.reload();
	})
	}
</script>

<div class="modal fade" id="view_potential" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/potentials/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-10">
			<div class="page-header">
				<h1><small>New Potential</small></h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-offset-2 col-lg-5">
			<%= form_for @potential do |f| %>
				<%= render 'form', :f => f, :potential => @potential %>
			<% end %>
		</div>
	</div>
</div>

app/views/potentials/show.html.erb
<h1>Potentials#show</h1>
<p>Find me in app/views/potentials/show.html.erb</p>

app/views/potentials/view_potential.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <h4 class="modal-title" id="myModalLabel">Potential Information</h4>
</div>
<div class="modal-body">
	<div class="form-group">
		<label>Title</label>
		<p><%= @potential.name %></p>
	</div>
	<div class="form-group">
		<label>Due Date</label>
		<p><%= @potential.amount %></p>
	</div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
  <%= link_to "Edit", edit_potential_path(@potential), class: "btn btn-warning" %>
</div>