config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
# Company
	resources :companies, only: [:new, :create] do
		collection do
			get 'welcome'
		end
	end

# Devise - User Authentication
  	devise_for :users

# Calendar
 	resources :calendars, only: [:index]

# Leads
	resources :leads do
		collection do
			get 'view_lead'
			get 'dashboard'
			get 'report'
		end
	end

# Accounts
	resources :accounts do
		collection do
			get 'view_account'
			get 'dashboard'
			get 'report'
		end
	end

# Contacts
	resources :contacts do
		collection do
			get 'view_contact'
			get 'dashboard'
			get 'report'
		end
	end

# Activities
	resources :phone_calls do
		collection do
			get 'view_call'
			get 'dashboard'
			get 'report'
		end
	end
	resources :events do
		collection do
			get 'view_event'
			get 'dashboard'
			get 'report'
		end
	end
	resources :tasks do
	  	collection do
	  		get 'view_task'
	  		get 'dashboard'
	  		get 'report'
	  	end
	end

# Invoices & Orders
	resources :purchase_orders do
		collection do
			get 'view_order'
			get 'dashboard'
			get 'report'
		end
	end
	resources :sales_orders do
		collection do
			get 'view_order'
			get 'dashboard'
			get 'report'
		end
	end
	resources :invoices do
		collection do
			get 'view_invoice'
			get 'dashboard'
			get 'report'
		end
	end

# Quotes and More
	resources :quotes do
		collection do
			get 'view_quote'
			get 'dashboard'
			get 'report'
		end
	end
	resources :price_books do
		collection do
			get 'view_book'
			get 'dashboard'
			get 'report'
		end
	end

# Vendor
	resources :vendors do
		collection do
			get 'view_vendor'
			get 'dashboard'
			get 'report'
		end
	end

# Products and More
	resources :products do
		collection do
			get 'view_product'
			get 'dashboard'
			get 'report'
		end
	end

	resources :cases do
		collection do
			get 'view_case'
			get 'dashboard'
			get 'report'
		end
	end

	resources :solutions do
		collection do
			get 'view_solution'
			get 'dashboard'
			get 'report'
		end
	end

# Potentials
	resources :potentials do
		collection do
			get 'view_potential'
			get 'dashboard'
			get 'report'
		end
	end

# Appointments
	resources :appointments do
		collection do
			get 'view_appointment'
			get 'dashboard'
			get 'report'
		end
	end

# Campaigns
	resources :campaigns do
		collection do
			get 'view_campaign'
			get 'dashboard'
			get 'report'
		end
	end

# Landing Page
root 'leads#index'

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

	# Relationship
	has_many   :purchase_orders
	has_many   :products
	has_many   :contacts
	belongs_to :company
	belongs_to :gl_account
	belongs_to :vendor_owner, class_name: "User", foreign_key: "owner"

	# Delegation
	delegate :name, to: :gl_account, prefix: true, allow_nil: true

	# Validations
	validates :name, presence: true
	validates :name, uniqueness: { scope: :company_id }
	validates :owner, presence: true
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  def index
    @vendors = current_company.vendors
  end

  def new
    @vendor = Vendor.new
  end

  def create
    @vendor = current_company.vendors.build(vendor_params)
    if @vendor.save
      redirect_to vendors_path
    else
      render :new
    end
  end

  def show
    @vendor = Vendor.find(params[:id])
  end

  def edit
    @vendor = Vendor.find(params[:id])
  end

  def update
    @vendor = Vendor.find(params[:id])
    if @vendor.update(vendor_params)
      redirect_to vendors_path
    else
      render :edit
    end
  end

  def destroy
    @vendor = Vendor.find(params[:id])
    @vendor.destroy
    redirect_to vendors_path
  end

  def view_vendor
    @vendor = Vendor.find(params[:id])
    render layout: false
  end

   # Dashboard
  def dashboard
    
  end

    # Report
  def report
    @vendors = current_company.vendors
    respond_to do |format|
      format.xlsx
    end
  end

  private

  def vendor_params
    params.require(:vendor).permit(:name, :owner, :phone, :email, :website, :gl_account_id)
  end
end

app/views/vendors/_form.html.erb
<div class="form-group">
	<label class="control-label">Vendor Name</label>
	<%= f.text_field :name, class: "form-control" %>
	<% if vendor.errors[:name].present? %>
    	<div class="error-message"><%=  vendor.errors[:name][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Owner</label>
	<%= f.collection_select :owner, User.all, :id, :email, {}, class: "form-control" %>
	<% if vendor.errors[:owner].present? %>
    	<div class="error-message"><%=  vendor.errors[:owner][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Phone</label>
	<%= f.text_field :phone, class: "form-control" %>
	<% if vendor.errors[:phone].present? %>
    	<div class="error-message"><%=  vendor.errors[:phone][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Email</label>
	<%= f.email_field :email, class: "form-control" %>
	<% if vendor.errors[:email].present? %>
    	<div class="error-message"><%=  vendor.errors[:email][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">Website</label>
	<%= f.text_field :website, class: "form-control" %>
	<% if vendor.errors[:website].present? %>
    	<div class="error-message"><%=  vendor.errors[:website][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<label class="control-label">GL Account</label>
	<%= f.collection_select :gl_account_id, GlAccount.all, :id, :name, {}, class: "form-control" %>
	<% if vendor.errors[:gl_account_id].present? %>
    	<div class="error-message"><%=  vendor.errors[:gl_account_id][0]%></div>
   	<% end %>
</div>
<div class="form-group">
	<%= f.submit "Save", class: "btn btn-warning" %>
	<%= link_to "Back", vendors_path , class: "btn btn-primary" %>
</div>

app/views/vendors/edit.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-10">
			<div class="page-header">
				<h1><small>Edit Vendor</small></h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-offset-2 col-lg-5">
			<%= form_for @vendor do |f| %>
				<%= render 'form', :f => f, :vendor => @vendor %>
			<% end %>
		</div>
	</div>
</div>

app/views/vendors/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<div class="page-header">
				<h1>
					<small><i class="fa fa-truck"></i> Vendor</small>
					<div class="pull-right">
						<%= link_to "<i class='fa fa-plus'></i> New Vendor".html_safe, new_vendor_path, class: "btn btn-warning btn-sm" %>
						<%= link_to "<i class='fa fa-bar-chart-o'></i> Dashboard".html_safe, dashboard_vendors_path, class: "btn btn-success btn-sm" %>
						<%= link_to "<i class='fa fa-file-excel-o'></i> Report".html_safe, report_vendors_path(:format => :xlsx), class: "btn btn-danger btn-sm" %>
					</div>
				</h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-offset-1 col-lg-10">
			<table class="table table-striped table-hover">
				<tr class="warning">
					<th></th>
					<th>Name</th>
					<th>Owner</th>
					<th>GL Account</th>
					<th>Actions</th>
				</tr>
				<% @vendors.each do |vendor| %>
					<tr>
						<td></td>
						<td><a href="#" onclick="get_click(<%= vendor.id %>);"><%= vendor.name %></a></td>
						<td><%= vendor.owner %></td>
						<td><%= vendor.gl_account_name %></td>
						<td>
							<%= link_to content_tag(:i,nil, class: 'fa fa-pencil'), edit_vendor_path(vendor), class: "btn btn-success btn-xs table-actions" %>
							<%#= link_to content_tag(:i,nil, class: 'fa fa-eye'), vendor_path(vendor), class: "btn btn-info btn-xs table-actions" %>
							<%= link_to content_tag(:i,nil, class: 'fa fa-trash'), vendor, class: "btn btn-danger btn-xs table-actions", method: :delete %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>	
</div>

<script type="text/javascript">
	function get_click(vendor){
	$('#view_vendor').modal({
  	 remote: "/vendors/view_vendor?id=" + vendor
	});
	$('#view_vendor').on('hidden.bs.modal', function () {
 	location.reload();
	})
	}
</script>

<div class="modal fade" id="view_vendor" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/vendors/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-10">
			<div class="page-header">
				<h1><small>New Vendor</small></h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-offset-2 col-lg-5">
			<%= form_for @vendor do |f| %>
				<%= render 'form', :f => f, :vendor => @vendor %>
			<% end %>
		</div>
	</div>
</div>

app/views/vendors/show.html.erb
<h1>Vendors#show</h1>
<p>Find me in app/views/vendors/show.html.erb</p>

app/views/vendors/view_vendor.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <h4 class="modal-title" id="myModalLabel">Vendor Information</h4>
</div>
<div class="modal-body">
	<div class="form-group">
		<label>Title</label>
		<p><%= @vendor.name %></p>
	</div>
	<div class="form-group">
		<label>Owner</label>
		<p><%= @vendor.owner %></p>
	</div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
  <%= link_to "Edit", edit_vendor_path(@vendor), class: "btn btn-warning" %>
</div>